import { ShieldCheck, Database, FileText, Sparkles, AlertTriangle } from 'lucide-react';
import type { ChampionshipDataSnapshot } from '../../types/f1';

interface ModelNotesPageProps {
  data: ChampionshipDataSnapshot | null;
}

export function ModelNotesPage({ data }: ModelNotesPageProps) {
  const archiveCoverage = data
    ? `${data.analyticsCoverage.indexedRaceResults}/${data.analyticsCoverage.totalCompletedRaceSessions}`
    : 'N/A';

  return (
    <div className="space-y-4 max-w-[1800px] mx-auto">
      <div className="border border-white/10 bg-graphite-light/40 p-5">
        <div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between">
          <div>
            <p className="text-[10px] tracking-[0.24em] text-white/40 uppercase">MODEL NOTES</p>
            <h1 className="mt-2 text-2xl font-black tracking-[0.08em] text-white">Product documentation</h1>
            <p className="mt-2 max-w-2xl text-sm text-white/50">Internal overview of APEX data sources, integrity protocol, model glossary, and responsible use guidelines.</p>
          </div>
          <div className="grid grid-cols-2 gap-3 text-[10px] text-white/40">
            <div className="rounded-sm border border-white/10 bg-black/20 p-3">
              <p className="uppercase tracking-[0.24em]">Version</p>
              <p className="mt-2 text-sm text-white">1.0.0</p>
            </div>
            <div className="rounded-sm border border-white/10 bg-black/20 p-3">
              <p className="uppercase tracking-[0.24em]">Archive</p>
              <p className="mt-2 text-sm text-white">{archiveCoverage} verified</p>
            </div>
          </div>
        </div>
      </div>

      <div className="grid gap-4 xl:grid-cols-3">
        <section className="rounded-sm border border-white/10 bg-black/20 p-5">
          <div className="flex items-center gap-2 text-white/70 mb-3">
            <FileText className="w-4 h-4 text-cyan" />
            <p className="text-sm tracking-[0.18em] uppercase">Product overview</p>
          </div>
          <p className="text-sm text-white/60 leading-relaxed">
            APEX is a portfolio-grade motorsport intelligence dashboard built with React, TypeScript, and Vite. It consumes verified OpenF1 session and championship data, applies local caching and archive indexing, and surfaces transparent insights without invented telemetry.
          </p>
        </section>

        <section className="rounded-sm border border-white/10 bg-black/20 p-5">
          <div className="flex items-center gap-2 text-white/70 mb-3">
            <Database className="w-4 h-4 text-cyan" />
            <p className="text-sm tracking-[0.18em] uppercase">Data integrity protocol</p>
          </div>
          <ul className="space-y-3 text-sm text-white/60 leading-relaxed">
            <li>APEX sources data from the OpenF1 public API and local snapshot cache only.</li>
            <li>Only official, completed sessions are used for standings and archive metrics.</li>
            <li>Race and standard qualifying archive handlers process indexed results progressively.</li>
            <li>Sprint sessions are excluded from key metrics unless explicitly available in the existing snapshot logic.</li>
            <li>Rate-limited source states pause live refresh and preserve cached verified snapshot data.</li>
            <li>Archive resume logic retries missing rounds instead of fabricating results.</li>
          </ul>
        </section>

        <section className="rounded-sm border border-white/10 bg-black/20 p-5">
          <div className="flex items-center gap-2 text-white/70 mb-3">
            <ShieldCheck className="w-4 h-4 text-cyan" />
            <p className="text-sm tracking-[0.18em] uppercase">Limitations</p>
          </div>
          <ul className="space-y-3 text-sm text-white/60 leading-relaxed">
            <li>APEX does not provide betting advice or title probabilities unless generated by existing model outputs.</li>
            <li>Live timing is only shown when actual session data is available; otherwise fallback labels are used.</li>
            <li>Partial archive conditions are clearly marked and do not drive speculative predictions.</li>
            <li>Values are derived from verified source data, cached snapshots, calendar entries, or archive index status.</li>
          </ul>
        </section>
      </div>

      <div className="grid gap-4 xl:grid-cols-2">
        <section className="rounded-sm border border-white/10 bg-black/20 p-5">
          <div className="flex items-center gap-2 text-white/70 mb-3">
            <Sparkles className="w-4 h-4 text-cyan" />
            <p className="text-sm tracking-[0.18em] uppercase">Metrics glossary</p>
          </div>
          <dl className="space-y-3 text-sm text-white/60 leading-relaxed">
            <div>
              <dt className="font-semibold text-white">Points position</dt>
              <dd>Current driver or constructor championship standing based on verified points.</dd>
            </div>
            <div>
              <dt className="font-semibold text-white">Average race finish</dt>
              <dd>Mean classified finish position from indexed verified race results.</dd>
            </div>
            <div>
              <dt className="font-semibold text-white">Average qualifying</dt>
              <dd>Mean qualifying position from indexed verified qualifying results.</dd>
            </div>
            <div>
              <dt className="font-semibold text-white">Completion rate</dt>
              <dd>Percentage of starts that resulted in a classified finish.</dd>
            </div>
            <div>
              <dt className="font-semibold text-white">DNF count</dt>
              <dd>Total retirements, DNS, or DSQ from indexed verified races.</dd>
            </div>
            <div>
              <dt className="font-semibold text-white">Performance index</dt>
              <dd>Normalized constructor score derived from points per round and reliability.</dd>
            </div>
          </dl>
        </section>

        <section className="rounded-sm border border-white/10 bg-black/20 p-5">
          <div className="flex items-center gap-2 text-white/70 mb-3">
            <AlertTriangle className="w-4 h-4 text-amber" />
            <p className="text-sm tracking-[0.18em] uppercase">Module map</p>
          </div>
          <ul className="space-y-3 text-sm text-white/60 leading-relaxed">
            <li><strong>Command Centre</strong>: Verified operations dashboard, event state, and archive feed.</li>
            <li><strong>Championship</strong>: Full season analysis with standings, constructors, timeline, and methodology.</li>
            <li><strong>Driver Intel</strong>: Detailed driver snapshot and teammate comparison from existing standings and race data.</li>
            <li><strong>Team Performance</strong>: Constructor-specific intelligence from verified points and archive coverage.</li>
            <li><strong>Circuit Matrix</strong>: Event-by-event calendar and verification status using actual race weekends.</li>
            <li><strong>Scenario Lab</strong>: Transparent title path index backed by available coverage and not claiming certainty.</li>
          </ul>
        </section>
      </div>
    </div>
  );
}
